#!/usr/bin/python

import requests
header={"Content-Type":"application/json"}
jsondata={
        "query":{
                "span_near":{
                        "clauses":[
                                {
                                        "span_multi":{
                                                "match":{
                                                        "regexp":{
                                                                "attachment.content":"[0-9]{3}"
                                                        }
                                                }
                                        }
                                },
                                {
                                        "span_multi":{
                                                "match":{
                                                        "regexp":{
                                                                "attachment.content":"[0-9]{2}"
                                                        }
                                                }
                                        }
                                },
                                {
                                        "span_multi":{
                                                "match":{
                                                        "regexp":{
                                                                "attachment.content":"[0-9]{4}"
                                                        }
                                                }
                                        }

                                }
                        ],
                        "slop":3,
                        "in_order": "true"
                }
        }
}
print jsondata

a=requests.get("http://localhost:9200/test/_search?pretty=true",headers=header,json=jsondata)

print a.text
